### ISSUE TITLE
(S3) USB-Serial devices section should have examples

### ISSUE THREAD

**Issue by thelionroars** [664306x/swin.edu.au-esp8266#14]
Examples of a couple of different USB-Serial TTL devices should be included, with photos

**Comment by 664306x** [comment]
Since its really one or the other (FTDI vs rigging a cable) ive only included these two. I dont think we really need a whole heap of examples of the same thing (lots of different FTDI boards). I think the one included gives enough of an idea (1. how to connect it, 2. it needs drivers, 3. use the jumper to 3.3v). Any features more advanced ones may have is irrelevant.

**Comment by thelionroars** [comment]
It's not even your section Luke. And what do you mean by rigging a cable?

**Comment by thelionroars** [comment]
Re-opened. I will mark this clearly as section 3. FYI, there are several chips available for USB-Serial TTL, referring to them all as FTDI is going to get confusing at some stage.

**Comment by thelionroars** [comment]
Mostly filled out, just need to check that the third adapter I have is fully working.

**Comment by thelionroars** [comment]
So the PL-2303HX-based adapter I have is working fine. I will take the photo when I have better lighting and close this.

**Comment by thelionroars** [comment]
Not the best photo, but it will have to do unless we have the opportunity to take a better one. Closed
